name: Deploy Maven App

on:
  push:
    branches:
      - terra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Maven Project
        run: mvn clean install -Dmaven.test.skip=true

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > aws_key.pem
          chmod 600 aws_key.pem

      - name: Deploy to AWS Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i aws_key.pem ubuntu@<YOUR_AWS_INSTANCE_IP> << 'EOF'
            echo "Connected to AWS instance"
            # Navigate to the app directory
            cd /var/www/html/app
            
            # Pull latest changes from Git (optional, if you're using Git to manage code)
            git pull origin terra
            
            # Restart your application or server
            pkill -f 'FinancialAdvisorChatbot-0.0.1-SNAPSHOT.jar' || echo "No instance running."
            nohup java -jar target/FinancialAdvisorChatbot-0.0.1-SNAPSHOT.jar &

            # Restart Apache (if needed)
            sudo systemctl restart apache2
          EOF

