name: Deploy Maven App

on:
  push:
    branches:
      - terra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Inject GitHub Secret for OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Build and run application
        run: |
          mvn clean install -Dmaven.test.skip=true
          java -jar target/FinancialAdvisorChatbot-0.0.1-SNAPSHOT.jar &
